Minh/Ben (readme update)
gitnamehere/point-of-sale-group-project pull request #5
Opened 2024-07-31 18:12 UTC by nhokzminh698

2024-07-31 20:54 UTC, gitnamehere requested changes

2024-07-31 20:54 UTC, gitnamehere commented on README.md
> +**- eCom:** http://localhost:3000/
I don't think we need these at the moment, since we are still deciding on the endpoints

2024-07-31 20:54 UTC, gitnamehere commented on README.md
> +- node server.js
Will be addressed in a separate PR, but the current scripts are:
Setup Postgres: `npm run setup`
Start server: `npm run start`

2024-07-31 20:54 UTC, gitnamehere commented on README.md
> +- PostgresSQL
nitpick: PostgreSQL

2024-08-01 02:17 UTC, gitnamehere approved these changes
lgtm

2024-08-01 21:19 UTC, andllrew approved these changes

2024-08-01 21:19 UTC, merged