Creating items
gitnamehere/point-of-sale-group-project pull request #9
Opened 2024-08-03 17:02 UTC by andllrew

**Ticket:** [Creating Items](https://cs375-pos-group-project.atlassian.net/jira/core/projects/ATS/board?selectedIssue=ATS-12)

**PR Desc:**

- Added a POST API endpoint to add items to the database `item` in server.js.
- Created an HTML page that owners will be directed to when they want to create an item.
- Created a local js file that will be multifunctional across different HTML pages.
- Added a fetch function that displays categories from the database `item_category`.
- Added a fetch function that sends item data to the backend POST body to add into the database `item`.

2024-08-03 22:33 UTC, gitnamehere requested changes
nice work, just have a few suggested changes here

2024-08-03 22:33 UTC, gitnamehere commented on app/public/pos/create.js
> +        }
You can use a ternary to shorten this down
```suggestion
        message.textContent = (response.ok ? "Success" : "Failure");
```

2024-08-03 22:33 UTC, gitnamehere commented on app/public/pos/create.js
> +});
add a new line here (a nitpick, but usually you want to end files with an empty line)

2024-08-03 22:33 UTC, gitnamehere commented on app/public/pos/create.html
> +</html>
nitpick: newline

2024-08-03 22:42 UTC, gitnamehere commented on app/public/pos/create.html
> +		<input id="name" type="text" name="name", size=40>
```suggestion
		<input id="name" type="text" name="name" maxlength="50">
```

2024-08-03 23:27 UTC, wetefok commented
I think it'd be best to move everything into a pos/item-management/ directory for better organization.

2024-08-04 01:08 UTC, gitnamehere commented on app/server.js
> +const { error } = require("console");
I think your vscode might've accidentally imported this

2024-08-04 01:10 UTC, gitnamehere approved these changes
FIRE CHANGES 🔥 LGTM

2024-08-04 01:13 UTC, nhokzminh698 approved these changes
ate the code up!!

2024-08-04 01:14 UTC, merged